import { FileBarChart, Download, Printer } from "lucide-react";
import { AppShell } from "@/components/maritime/AppShell";
import { PageHeader } from "@/components/maritime/PageHeader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const Reports = () => {
  return (
    <AppShell>
      <div className="px-6 md:px-10 py-8 max-w-6xl mx-auto">
        <PageHeader
          eyebrow="Export"
          title="Operational Reports"
          description="Print-ready operational handover reports with extraction, risks, critic notes and eval metrics. Export ships in Phase 7."
          actions={
            <>
              <Button disabled variant="outline">
                <Printer className="mr-1 h-4 w-4" /> Export PDF
              </Button>
              <Button disabled>
                <Download className="mr-1 h-4 w-4" /> Download JSON
              </Button>
            </>
          }
        />

        <div className="panel p-8">
          <div className="flex items-start justify-between gap-4 border-b border-border pb-6 mb-6">
            <div>
              <div className="text-[11px] uppercase tracking-[0.2em] text-primary/80 mb-1">
                Operational Handover Report
              </div>
              <h2 className="text-xl font-semibold">MV Northern Pioneer · Voyage V-2026/041</h2>
              <p className="text-xs text-muted-foreground mt-1">
                Generated by MaritimeOps AI Copilot · Synthetic preview
              </p>
            </div>
            <div className="flex flex-col items-end gap-2">
              <Badge variant="outline" className="border-success/40 bg-success/10 text-success">
                Critic: Pass
              </Badge>
              <span className="mono text-xs text-muted-foreground">REPORT-2026-041</span>
            </div>
          </div>

          <div className="grid gap-6 md:grid-cols-3 mb-6">
            {[
              ["Vessel", "MV Northern Pioneer"],
              ["Route", "Rotterdam → Singapore"],
              ["Cargo", "55,000 MT HSFO"],
              ["Laycan", "12 – 18 Jun 2026"],
              ["Demurrage", "USD 24,500 / day"],
              ["Governing Law", "English (LMAA)"],
            ].map(([k, v]) => (
              <div key={k}>
                <div className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  {k}
                </div>
                <div className="mono text-sm mt-1">{v}</div>
              </div>
            ))}
          </div>

          <div className="space-y-3">
            <h3 className="text-sm font-semibold">Headline risks</h3>
            <ul className="space-y-2 text-sm">
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-[hsl(var(--high))]" />
                Discharge port agent missing — escalate to chartering before ETA.
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-warning" />
                Ambiguous laytime commencement clause.
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-muted-foreground/60" />
                Despatch wording open to interpretation.
              </li>
            </ul>
          </div>

          <div className="mt-8 text-xs text-muted-foreground border-t border-border pt-4 flex items-center gap-2">
            <FileBarChart className="h-3.5 w-3.5" />
            Phase 7 will add a print stylesheet, JSON export of the full{" "}
            <span className="mono text-foreground/80">AnalysisRun</span>, and a
            shareable read-only link.
          </div>
        </div>
      </div>
    </AppShell>
  );
};

export default Reports;
